//Copyright timeanddate.com 2005-2011, do not use without permission
var calobj=null,origbu="",cactive="",cibso=0,cibsa=0;function gcf(){return document.cf}function rrb(a,c){var b,d;for(d=0;d<20;d++)if((b=a[c+d])&&b.checked)return b.value;return-1}function chv(a){var c=arguments,b,d=c.length,f=[],e;for(b=1;b<d;b++){e=c[b];f[e]=gfv(a[e])}return f}function ca_d(a){return chv(a,"cdt","ccc","ccd","ccf","ccg","cci","ccj","ccl","ccp","ccu","ccz")}
function cgy(a){var c=a.value;if(c>=1&&c<=3999){sem(a,"");return c}if(c<0||c>3999)sem(a,"year must be between 1 and 3999");else{c=c.replace(/\s/g,"");c!==""&&sem(a,"Invalid value, year must be between 1 and 3999")}return(new Date).getFullYear()}
function ccm(){var a,c=gcf(),b,d=c.typ.value;if(d===0)return 12;if(d==1)return 1;a=c.y2;b=(cgy(a)-cgy(c.fyear)+1)*12;if(d==2)b+=c.m2.value-c.fmonth.value-11;if(b>36){sem(a,"You can create 3 years or 36 months only");return 36}if(b<1){sem(a,"End date is before start date");return 1}sem(a,"");return b}
function cprevf(){function a(q){j--;g++;if(q++<h)b[f++]="<td title='Month number "+q+"'>"+q+"</td>"}var c=gcf(),b=[],d=rrb(c,"display"),f=1,e,h=ccm(),j=h,k,g=0;e="cs"+d;var m=c.cols.value,l=c.pbr.value-0,n=1,o;c=c.cold.value;if(m<=0)m=3;if(d==1)m=1;for(l||(l=Math.floor((j-1)/m)+1);j>0;){b[f++]="<table class='"+e+"'><tr><th colspan='"+m+"'>Page&nbsp;"+n++ +"</th></tr>";o=0;d=g;k=Math.floor((j-1)/m)+1;if(k<l)l=k;for(;j>0&&o<l;){b[f++]="<tr>";if(c>0)for(k=0;k<m;k++)a(d+k*l+o);else for(k=0;k<m&&j>0;k++)a(g);
b[f++]="</tr>";o++}b[f++]="</table>"}e=b.join("");iH("prevf",e)}function ctyp(){var a=gcf().typ.value-0;he("ryear",a<2);he("rmonth",a==1);he("rfyear",a>1);he("rfmonth",a==2||a==4);he("rfdate",a==4);he("ry2",a>1);he("rm2",a==2||a==4);he("rd2",a==4);cprevf()}function cpo(a,c){var b=gf("cpop"),d=b.style;sd(b,2);ih(b,c);d.left="1%";d.top=po(a).y+"px";d.width="98%"}function cpc(){var a=gf("cpop");sd(a,0);cactive=""}
function tbc(a){for(var c=1,b;b=gf("t"+c);){b.className=a==c?"act":"";if(b=gf("cf"+c))b.style.display=a==c?"":"none";c++}cpc();return false}function chopt(){var a=gcf(),c=false,b=false,d=false;if(a){if(a.typ[0].checked)b=c=true;if(a.typ[1].checked)b=d=true;he("month",c);he("months",b);he("cols",d)}}function chco(){var a,c,b=gcf();if(b){a=b.country;a[a.selectedIndex].text="Changing - Please wait...";a=location.href;c=a.indexOf("?");if(c>0)a=a.substring(0,c);b.action=a;b.submit()}}
function cper(){cprevf()}function ccst(){var a;if(a=gcf().cst){a=a.selectedIndex;he("tstates",a==3)}}function cspace(){}function ccols(){cprevf()}function ccold(){cprevf()}function cdisplay(){var a=gcf(),c=rrb(a,"display")!=1;ee(a,"cols",c);ee(a,"cold",c);cprevf()}function holchg(){var a,c,b,d=gcf();if(c=d.hol){a=c.options.length-1;a=c.selectedIndex==a;he("customhol",a);for(c=a=0;c<30;c++)if(b=d["h"+c])if(b.checked)a+=1<<c}}function wnochg(){var a=gcf().wno;a&&he("wnodiv",gso(a).value==6)}
function csm(a,c){var b,d;for(d=1;d<100;d++){b=gf(a+d);if(!b)break;b.className=c}}function cac(a,c,b){return(a=a[c])?" "+c+a+(b?b:""):""}
function cgc(a){var c,b,d,f,e=[];if(c=cdt_a[a.cdt]){c=c.match(/(\w+\d+)/g);d=c.length;for(b=0;b<d;b++)e[c[b].substring(0,2)]=c[b].substring(2)}for(f in a){p=a[f]-0;if(p>0)e[f.substring(1,3)]=p}a=cac(e,"cf")+cac(e,"cz");f=cac(e,"cc")+cac(e,"cd")+cac(e,"cg")+a+cac(e,"ci")+cac(e,"cj")+cac(e,"cu");return{m:"ct1"+cac(e,"cp")+cac(e,"cl")+f,h:"ch ch1"+cac(e,"cl","h")+f,t:a}}
function cprevc(a){var c,b,d;b=gcf();cactive&&cpc();if(a=="cdt"){a=["ccc","ccd","ccf","ccg","cci","ccj","ccl","ccp","ccu","ccz"];c=a.length;for(d=0;d<c;d++)b[a[d]].selectedIndex=0}b=ca_d(b);b=cgc(b);csm("mct",b.m);csm("ch",b.h);csm("ct",b.t)}function cps(a,c){var b,d,f,e,h;if(c>=0){b=gcf();b=b[a];d=b.options;f=d.length;for(e=0;e<f;e++){h=d[e].value;if(h==c)b.selectedIndex=e}}gf(a+"_p").value=origbu;cprevc()}
function cto_o(){var a,c=rs4(calobj);if(c){he("cts",0);a="";c=c.replace(/\<scrip[t][^>]*>((.|\n)*?)<\/script>/g,function(b,d){a+=d;return""});a=a.replace("<!--","").replace("--\>","");iH("ctti",c);eval(a);calinit();tbc(1)}}function cjx(a,c,b){if(!a)a=location.search;a="/calendar/createcal2.php?smode="+c+"&"+(a?a.replace(/\?/,""):"");if(calobj=gx()){gp(calobj,a,b);return false}}function csw(a){cpo(gf(a),"<div class='clo'>Please wait while loading...</div>")}
function ctcl(){cpc();he("ctt",0);he("cts",1)}function cto(a){he("ctt",2);csw("ctt");return cjx(a,"tab",cto_o)}function cto1(a,c){var b,d,f,e,h=ga(document.f1);h.typ=a;h.display=c;if(b=gf("ctlink").href.match(/(\w+\=[^\&]+)/g))for(d=0;d<b.length;d++){f=b[d];if(e=f.indexOf("="))h[f.substring(0,e)]=f.substring(e+1)}b=au(h);return cto(b)}function cochg(){var a=ga(gcf());a=au(a);cto(a)}
function cdtac(){var a,c,b=gcf().cdta;if(b){a=b.checked;for(b=b.parentNode.parentNode;b=b.nextSibling;)(c=b.style)&&sd(b,a)}}function csp_o(){var a=rs4(calobj);if(a){ee(gcf(),"cspb",1);iH("calarea",a);cpc()}}function csp(){var a;csw("cspb");a=gcf();ee(a,"cspb",0);a=ga(a);a=au(a);return cjx(a,"prv",csp_o)}function gfn(a,c){var b,d,f;if(a){d=a.childNodes;f=d.length;for(i=0;i<f;i++){b=d.item(i);if(b.tagName==c)return b}}}
function cib(a,c,b){return"<input title='"+a+"' type='button' value='"+c+"' onclick='"+b+"''>"}function acibs(){var a,c,b,d,f=gf("cprevt");if(f){a=f.scrollLeft;c=cibso-a;b=Math.abs(c);d=c>0?1:-1;c=Math.floor(Math.pow(b,0.7));if(c>cibsa)c=cibsa+15;cibsa=c;a=a+c*d;f.scrollLeft=a;a!=cibso&&setTimeout("acibs()",10)}}function cibs(a){var c,b,d;if(d=gf("cprevt")){c=d.clientWidth;b=d.scrollLeft;d=d.scrollWidth;d=d-c;c-=240;if(c<120)c=120;b+=c*a;if(b<0)b=0;if(b>d)b=d;cibso=b;acibs()}}
function cprevv(a,c){var b,d,f,e,h,j,k,g;e=gcf();g=a.id;b=g.indexOf("_");g=g.substring(0,b);if(cactive){b=g==cactive;cps(cactive,-1);if(b)return}b=gf("caltemp").innerHTML;d=gf(g+"_p");f=e[g].options;cactive=g;if(!origbu)origbu=d.value;d.value="Close Preview";var m=g=="cdt"?{}:ca_d(e),l=[],n=0;l[n++]="<div class='cpreva'>"+cib("Scroll back","&lt;&lt; Scroll back","cibs(-1)")+"</div><div class='cprevb'>"+cib("Scroll forward","Scroll forward &gt;&gt;","cibs(1)")+"</div>";l[n++]="<div id='cprevt' class='cprevt'><table><tr id='prevr'>";
e=0;for(b=b.replace(/\=REPL/,"='REPL'");e<=c;e++){h=f[e];j=h.value;m[g]=j;k=cgc(m);k=b.replace(/REPL/,k.m);l[n++]="<td><div class='cprevd'>"+cib("",h.text,'cps("'+g+'",'+j+")")+"<div class='cprevdd'>"+k+"</div></div></td>"}l[n++]="</tr></table></div>";cpo(d,l.join(""));if(e=gf("prevr")){g=e.cells;c=g.length;for(e=0;e<c;e++){b=g.item(e);b=gfn(b,"DIV");if(d=gfn(b,"DIV")){f=d.firstChild.scrollWidth;d.style.width=f+"px";if(f<230){f+=10;b.style.width=f+"px"}}}}}
function ea(a,c){var b,d,f,e=[],h=0,j,k=arguments,g;if(a)for(j=2;j<k.length;j++)if(b=a.getElementsByTagName(k[j])){d=b.length;for(g=0;g<d;g++){f=b.item(g);if(c(f))e[h++]=f}}return e}function ca_f(a){a=a.type;return a=="select-one"||a=="text"}
function calinit(){var a,c,b,d,f,e;for(a=1;a<=9;a++){c=gf("cf"+a);c=ea(c,ca_f,"input","select");d=0;e=c.length;for(b=0;b<e;b++){f=c[b].offsetWidth;if(f>d)d=f}for(b=0;b<e;b++){f=c[b].offsetWidth;if(f<d)c[b].style.width=d+"px"}}ccst();ctyp();holchg();wnochg();cprevf();cdtac();(function(){function h(j){ael(gf(j),"focus",cper);ael(gf(j),"blur",cper);elc[j]=cper}h("year");h("fdate");h("fyear");h("d2");h("y2")})()};
