//Copyright timeanddate.com 2005-2011, do not use without permission
men={};menact=null;elh={};elc={};fh={};ph={};
menus=[{p:"/",s:[{t:"Newsletter",u:"newsletter/"},{t:"About Us",u:"information/"},{t:"Site Map",u:"sitemap.html"}]},{p:"/worldclock/",s:[{t:"Main World Clock",u:""},{t:"Extended World Clock",u:"full.html"},{t:"Personal World Clock",u:"personal.html"},{t:"Event Time Announcer",u:"fixedform.html"}]},{p:"/",s:[{t:"Time Zone Converter",u:"worldclock/converter.html"},{t:"Meeting Planner",u:"worldclock/meeting.html"},{t:"Time Zone Abbreviations",u:"library/abbreviations/timezones/"},{t:"Time Zone News",
u:"news/time/"},{t:"Daylight Saving Time",u:"time/dst/"}]},{p:"/",s:[{t:"Calendar 2011",u:"calendar/?year=2011"},{t:"Calendar 2012",u:"calendar/?year=2012"},{t:"Choose any Month",u:"calendar/monthly.html"},{t:"Basic Creator",u:"calendar/basic.html"},{t:"Advanced Creator",u:"calendar/custommenu.html"},{t:"Holidays Worldwide",u:"holidays/"}]},{p:"/w",s:[{t:"Worldwide",u:"eather/"},{t:"Local Weather",u:"orldclock/goweather.php"},{t:"2-week Forecast",u:"orldclock/goweather.php?type=ext"},{t:"Hour-by-hour",
u:"orldclock/goweather.php?type=hourly"},{t:"Past Week",u:"orldclock/goweather.php?type=historic"}]},{p:"/",s:[{t:"Sun Calculator",u:"worldclock/sunrise.html"},{t:"Moon Calculator",u:"worldclock/moonrise.html"},{t:"Moonphases",u:"calendar/moonphases.html"},{t:"Seasons",u:"calendar/seasons.html"},{t:"Day and Night Map",u:"worldclock/sunearth.html"},{t:"Eclipses",u:"eclipse/"}]},{p:"/",s:[{t:"Countdown to Any Date",u:"counters/customcount.html"},{t:"New Year Countdown",u:"counters/newyear.html"},{t:"Stopwatch",
u:"stopwatch/"},{t:"Timer",u:"timer/"}]},{p:"/",s:[{t:"Date to Date Calculator",u:"date/duration.html"},{t:"Date Calculator",u:"date/dateadd.html"},{t:"Dialing Codes",u:"worldclock/dialing.html"},{t:"Distance Calculator",u:"worldclock/distance.html"},{t:"Travel Time Calculator",u:"time/travel.html"}]},{p:"/",s:[{t:"iPad Apps",u:"ipad/"},{t:"iPhone Apps",u:"iphone/"},{t:"Facebook Apps",u:"facebook/"},{t:"Free Clock for your Site",u:"clocks/free.html"},{t:"Free Countdown for your Site",u:"clocks/freecountdown.html"}]}];
Mf=Math.floor;function pf(a,b){for(;(a="0000"+a)&&a.length<b;);return a.substring(a.length-b)}function p2(a){return a<10?"0"+a:a}function lim(a,b,c){return Math.max(Math.min(a,c),b)}function dt(){return(new Date).getTime()}function gf(a){var b=document;if(b.getElementById)return b.getElementById(a);if(b.all)return b.all[a];return null}function ih(a,b){if(a)a.innerHTML=b}function iH(a,b){ih(gf(a),b)}function sd(a,b){if(a)a.style.display=b?b==2?"block":"":"none"}function he(a,b){sd(gf(a),b)}
function ee(a,b,c){if(a=a[b])a.disabled=!c}function ac(a,b,c){var d,e,f;if(a){d=a.className+" ";e=" "+d;f=e.indexOf(" "+b+" ");if(c){if(f>=0)return;d+=b}else{if(f<0)return;d=d.substring(0,f)+e.substring(f+b.length+1)}a.className=d}}function wl(a){var b=window.location;if(a)b.href=a;return b}sem_a={};function sem(a,b){var c,d;d=a.name;c="e"+d;if(sem_a[d]!=b){sem_a[d]=b;c=gf(c);d=gf(d);if(c){ih(c,b);ac(c,"errmark",b)}d&&ac(d,"errf",b)}}
function gx(){function a(e){try{if(c.ActiveXObject)return new ActiveXObject(e)}catch(f){}}var b=null,c=window;try{if(c.XMLHttpRequest)b=new XMLHttpRequest}catch(d){}b||(b=a("Msxml2.XMLHTTP"));b||(b=a("Microsoft.XMLHTTP"));return b}function gp(a,b,c){if(a)try{a.open("GET","http://"+document.domain+b,true);a.onreadystatechange=c;a.send("");return 1}catch(d){alert(d)}return 0}
function rs4(a){if(a&&a.readyState==4)if(a.status!==200){errm="rs4:status="+a.status;return}else return a.responseText+"";return false}function po(a){for(var b={x:0,y:a.offsetHeight};a;){b.x+=a.offsetLeft;b.y+=a.offsetTop;a=a.offsetParent}return b}function gso(a){return a.options[a.selectedIndex]}
function gfv(a){var b=a.type;if(b)switch(b){case "select-one":return gso(a).value;case "text":case "hidden":return a.value;case "radio":if(a.checked)return a.value;break;case "checkbox":return a.checked?a.value:"";case "button":case "submit":break;default:alert("Unknown type "+b)}return null}function ga(a){var b=[],c=a.elements,d=c.length,e,f;for(e=0;e<d;e++){a=c[e];f=gfv(a);if(f!==null)b[a.name]=f}return b}function au(a){var b=[],c=0,d;for(d in a)b[c++]=d+="="+escape(a[d]);return b.join("&")}
function ap(a){for(var b=0,c=0;a;){b+=a.offsetLeft;c+=a.offsetTop;a=a.offsetParent}return{x:b,y:c}}function ep(a,b){var c=a.style;c.left=b.x+"px";c.top=b.y+"px"}
function gcs(a,b){var c,d,e,f;f=window.getComputedStyle;var g=function(k,h){c=/^\d+(px)?$/i;if(parseFloat(h)>0){if(c.test(h))return parseInt(h);d=k.style.left;e=k.runtimeStyle.left;k.runtimeStyle.left=k.currentStyle.left;k.style.left=h||0;h=k.style.pixelLeft;k.style.left=d;k.runtimeStyle.left=e}else h=0;return h};if(f){if(f=f(a,null))return g(a,f.getPropertyValue(b))}else if(f=a.currentStyle){f=f[b];if(b=="height"&&f=="auto")f=a.offsetHeight-gcs(a,"marginTop")-gcs(a,"marginBottom");return g(a,f)}return null}
function es(a,b){var c=a.style;if(b.w>0)c.width=b.w+"px";if(b.h>0)c.height=b.h+"px"}function it(a,b){var c,d;if(a){c=a.length;for(d=0;d<c;d++)b(a[d],d)}}function sw(a){var b,c=[],d=0;it(a,function(e,f){c[f]=e;b=e.offsetWidth;if(b>d)d=b});it(c,function(e){es(e,{w:d})})}function ghj(a){var b,c,d={j:""};b=a.indexOf("<script>");if(b>=0){c=a.indexOf("<\/script>",b);if(c>0){d.j+=a.slice(b+9,c);a=a.slice(0,b)+a.slice(c+10)}}d.h=a;return d}
function jp(a,b,c,d,e){var f=b.offsetWidth,g=c.offsetWidth;c=c.offsetHeight;if(d==-1)a.x-=f-g;if(d==1)a.x+=g;if(d==2)a.x+=(g-f)/2;if(e==-1)a.y-=c;if(e==1)a.y+=c;if(e==2)a.y+=(c-b.offsetHeight)/2;if(a.x<0)a.x=0}function ru(a,b){var c,d,e,f=b.split("&");a=a.replace(/\?/,"?&");for(e=0;e<f.length;e++){c=f[e];d=c.indexOf("=");if(d>0){d=c.substr(0,d+1);d=a.indexOf("&"+d);if(d>0)a=a.substring(0,d+1)+c+a.substring(d+1);else a+="&"+c}}return a.replace(/\?\&/,"?")}
function hu(a){return a.replace(/\&/,"&amp;")}function siv(a){var b=document.body,c=b.scrollLeft,d=b.scrollTop,e=b.clientWidth,f=b.clientHeight,g=ap(a),k=a.clientWidth;a=a.clientHeight;var h=0,l=0;c=g.x-c;if(c<0)h=c;c+=k-e;if(c>0)h=c;c=g.y-d;if(c<0)l=c;c+=a-f;if(c>0)l=c;if(h)b.scrollLeft+=h;if(l)b.scrollTop+=l}function ael(a,b,c,d){if(a)if(a.addEventListener)a.addEventListener(b,c,d);else a.attachEvent&&a.attachEvent("on"+b,c)}
function oael(a,b,c,d){var e;e=a.id;if(!e)e=a.name;if(!e)e=a.href;e=b+":"+e;if(!elh[e]){elh[e]=1;ael(a,b,c,d)}}function PU(a){this.n=a;this.s=0}PU.prototype.h=function(a){var b=gf(this.n);this.e=b;this.s=-1;ih(b,a);sd(b,2);return b};PU.prototype.k=function(){sd(this.e,0);this.s=0;this.c&&this.c()};PU.prototype.x=function(a){a&&a!=this.s||this.s>=0&&this.k()};PU.prototype.y=function(){this.s=-1};
PU.prototype.z=function(a){var b,c;a||(a=500);b=dt()+a;c=this;c.s=b;window.setTimeout(function(){c.x(b)},a+100)};PU.prototype.A=function(a,b,c){a=ghj(a);var d=this.h(a.h),e=ap(b);jp(e,d,b,c?c:0,1);ep(d,e);eval(a.j)};pM=new PU("po1");nM=new PU("ho");nM.c=function(){if(this.li){ac(this.li,"hovact",0);this.li=0}};function mena(a,b){var c;b.n=a;c=a.indexOf("txt");if(c>0)b.N=a.slice(0,c);men[a]=b}
function menh(a){var b,c=menact;if(c)if(b=c.e.getElementsByTagName("li")){var d=function(e,f){typeof e!="undefined"&&e>=0&&e<b.length&&ac(b[e],"h",f)};d(c.h,0);d(a,1);c.h=a}}function mech(a,b){var c;if(b)if(a.f)a.f(a,b);else{a.i.value=b.n;if(a.g&&b.U)wl(b.U);else{if(a.I){a.I.value=b.U;c=fh[a.n];c.H=b.U;c.T=b.n}va(a.i.id)}}pM.k()}function menc(a){var b=menact;if(b){a=b.a[a];mech(b,a)}}
function mens(a,b){var c,d,e,f,g,k,h,l,u,s,o,n,v,y,p,m=men[a];if(m){c=ap(b);d=m.u?m.u.replace(/\&amp\073/g,"&"):"/";e=m.a;f=0;g=m.c?m.c:"mn";k=m.C?m.C:g;g="<div class="+g+" onmouseout='pM.z()'>";h=e.length;l=m.r;u=0;s=l&&l<h;o=1;if(s){o=Mf((h+l-1)/l);g+="<table><tr>"}else l=h;for(;o--;){u+=l;if(s)g+="<td valign=top>";for(g+="<ul class="+k+">";f<h&&f<u;f++){n=e[f];if(n.s==1)g+="<li class=mnd>&nbsp;";else{v="";if(n.p)v=hu(ru(d,n.p));if(n.u)v=n.u;y=(y=(o?"lr":"")+(f==l-1?" ls":""))?"class='"+y+"' ":
"";p="h";if(n.s)p+=" asb";g+="<li onmouseover='pM.y()'"+(n.h?" class='"+p+"' ":"")+">";p=n.n+(n.d?n.d:"");if(n.c)p="<span class="+n.c+">"+p+"</span>";if(n.s!=2)if(v)p="<a "+y+"href='"+v+"'>"+p;else if(m.i||n.v)p="<a "+y+"href='javascript:menc("+f+")'>"+p;g+=p;if(n.x)g+="<span class=mnx>"+n.x+"</span>";g+="</a>"}g+="</li>"}g+="</ul>";if(s)g+="</td>"}if(s)g+="</tr></table>";menact=m;d=pM.h(g);m.e=d;if(m.i){d.style.width="";e=d.offsetWidth;f=m.i.offsetWidth;e<f&&es(d,{w:f});if(m.N)m.I=m.i.form[m.N]}jp(c,
d,b,typeof m.j!="undefined"?m.j:-1,1);ep(d,c);siv(d)}}
function ifd(a){var b,c,d,e,f,g,k,h,l,u,s,o,n,v,y,p,m,H,I,K,Q,L,A,R,S,E,B,M,t,z,N,T,O,F,C=a.f,x=C.value,i=a.n.indexOf("txt");if(i>0)if(b=C.form[a.n.slice(0,i)]){c=":";if(a.H&&a.T){d=a.T.toLowerCase();_B=x.toLowerCase();if(_B.indexOf(d)>=0)c=a.H}b.value=c}if(a.e){_M=a.t;_G=0;b=11;var w={i:C,a:[]};J=function(r,q){e=q.s;e+=e?" - "+q.c:q.c;r.a[r.a.length]={c:"ash",n:q.n,x:e,U:q.i,h:0,d:q.f?"<img height=16 width=16 class=fr alt=Flag src='"+q.f+"'>":""}};D=function(){a.m=w;a.u=-1;mena(a.n,w);mens(a.n,C)};
j=function(r,q){f=r.indexOf(q);if(f<0)return 0;g=q.length;if(f===0)return g;if(r.charCodeAt(f-1)<65)return g*0.9;k=q.length;if(k<2)return 0;g*=(k+0.1)/(k+5);r=r.substr(0,f);if(h=r.match(/([\040-\077]+)/))return 0.5*g/(1+h.length);return 0.1};X=function(){return{i:C,a:[],c:"as",C:"asu",g:0,j:0}};var G=function(r){if(r){_F=X();if(a.s)_F.g=1;a.p=r;if(_E=r.length){l=z.split(/\s+/);u=l.length;_H=[];for(i=0;i<_E;i++){o=r[i];for(s=v=n=0;s<u;s++){_L=l[s];y=" "+_L+" ";_K=(o.o==_L)*10+(o.a==_L)*5;p=o.x.indexOf(y)>=
0;if(o.t.indexOf(_L)>=0||o.e.indexOf(_L)>=0||o.u.indexOf(_L)>=0||p){m=j(o.t,_L)*10;H=j(o.e,_L)*5;I=j(o.u,_L)*4;if(p&&_K<10)_K=10+o.z;if(m>_K)_K=m;if(H>_K)_K=H;if(I>_K)_K=I}if(_K){v++;n+=_K}}if(n>0){K=v/u;_H[_H.length]={w:v,s:(o.p*3+n)*K*K,c:o}}}_H.sort(function(q,P){return P.s-q.s});_E=_H.length;if(_E>20)_E=20;if(_E>0){Q=_E>5?5:_E;A=_H[0].s;R=A*0.7;S=A*0.2;E=1;B=0;for(i=1;i<_E;i++){L=A;A=_H[i].s;if(A<S){_E=i;break}M=L-A;if(i<Q&&M>E&&L>R){E=M;B=i}}if(B>3||E<1.2)B=0;if(B){for(i=0;i<B;i++)J(_F,_H[i].c,
1);_F.a[_F.a.length]={s:1}}_H=_H.slice(B,_E);_E=_H.length;_H.sort(function(q,P){return q.c.n.localeCompare(P.c.n)});for(i=0;i<_E;i++)J(_F,_H[i].c,0)}else _F.a[0]={n:"No matches",s:2,h:0,c:"ash"};if(a.s)_F.a[_F.a.length]={u:"/worldclock/",n:"World Clock",s:100,h:1};w=_F}}};if(_M.length==1){c=x=x.replace(/[^\d]/g,"");_C=new Date;d=2;a.i=1;if(_M=="y"){_G=_C.getFullYear()-5;d=x.length;if(d>0){if(d<4)x+="1005".slice(d);_G=x.slice(0,4)-5}a.a=3999;d=4}if(_M=="m"){_G=1;b=12;a.a=12;t=["","Jan","Feb","Mar",
"Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"]}if(_M=="d"){_G=1;b=31;a.a=31;w.r=10}_G=lim(_G,1,3989);if(_M=="i"||_M=="s"){_G=0;b=60;a.i=0;a.a=59;w.r=10}if(_M=="h"){_G=0;b=24;a.i=0;a.a=23;w.r=12;t=[];for(i=0;i<b;i++)t[i]=(i+11)%12+1+(i<12?"am":"pm")}for(i=0;i<b;i++){_A=t?" - "+t[_G]:"";w.a[w.a.length]={n:pf(_G,d),d:_A,h:c==_G};_G++}}if(_M.length==2){a.l=1;if(a.o)return;else if(_M=="ci"){x=x.replace(/^\s+/g,"").replace(/\s+$/g,"").replace(/\s+/," ");if(!a.c)a.c={};z=x.toLowerCase();t=a.c[z];
if(z&&z.length>=2)if(t)t.d?G(t.d):G(a.p);else{t="/worldclock/wcauto.php?query="+encodeURIComponent(z);if(a.x)t+="&xd="+a.x;if(N=gx()){a.c[z]={};gp(N,t,function(){if(T=rs4(N)){O=T.split("\n");i_count=O.length;F=[];for(i=0;i<i_count;i++){_D=O[i].split("\t");if(_D.length>7)F[i]={i:_D[0],p:_D[1],o:_D[2],a:_D[3],n:_D[4],s:_D[5],c:_D[6],f:_D[7],t:_D[4].toLowerCase(),e:_D[5].toLowerCase(),u:_D[6].toLowerCase(),x:" "+_D[8]+" ",z:_D[9]-0}}a.c[z].d=F;G(F);D()}})}G(a.p)}else{pM.k();return}if(w.a.length===0)w.a[0]=
{n:"Loading...",s:2,c:"ash"}}}D()}}function ifku(a){return ifd(a)}function ifpd(a){a.preventDefault&&a.preventDefault();a.returnValue=false}
function ifkd(a,b){var c,d,e,f,g,k,h;h=a.f;g=true;k=(d=window.event)?d.keyCode:b.which;c=a.u;d=a.m;e=a.l&&d;f=0;if(k==27){a.e=0;pM.k()}if(k==38)f=-1;if(k==40)f=1;if(f)if(e){g=d.a.length-1;for(k=0;k<3;k++){if(c==-1){a.o=h.value;c=f>0?0:g}else c+=f;if(c>g)c=-1;if(c==-1||!d.a[c].s)break}h.value=c>=0?d.a[c].n:a.o;if(c<0)a.o=null;a.u=c;menh(c);return false}else{d=h.value-0;if(d>=0)d+=f;a=fh[h.name];if(!a||!a.a||a.i<=d&&a.a>=d){h.value=d;g=false}}else if(k==13){if(c>=0)if(e){h=d.a[c];mech(d,h);ifpd(b);
return false}}else a.o=null;ifd(a);return g}function ifs(a){var b=a.u;if(a.s&&b>=0)return false;return true}function ifcb(){pM.z(50)}function aau(a){it(a.elements,function(b){b.setAttribute("autocomplete","off")})}function dau(a){it(a.elements,function(b){b.removeAttribute("autocomplete")})}
function ifc(a,b,c,d){var e;e=a.name;var f=fh[e];if(!f){f={n:e,f:a,t:b};fh[e]=f;b=e.indexOf("txt");if(b>0){e=e.slice(0,b);if(e=a.form[e]){f.H=e.value;f.T=a.value}}oael(a,"keydown",function(g){ifkd(f,g)},0);oael(a,"keyup",function(g){ifku(f,g)},0);oael(a,"blur",function(g){ifcb(a,f,g)},0);if(c){f.s=1;oael(a.form,"submit",function(){return ifs(f)})}if(d)f.x=d}f.e=1;return ifd(f)}
function om(a,b){var c,d,e,f,g;c=menus[b];e=c.p;var k=c.s,h=k.length,l="";oael(a,"mouseout",function(){nM.z()},0);nM.c();nM.li=a.parentNode;ac(nM.li,"hovact",1);if(h){for(f=0;f<h;f++){g=f?f==h-1?"id=mil":"":" id=mif";c=k[f];d=(d=c.u)?e+d:e;l+="<li><a href='"+d+"' onmouseover='nM.y()'"+g+">"+c.t+"</a></li>"}c=nM.h(l);e=po(a);e.x-=2;ep(c,e);nM.y()}}blo=-1;
function bls(a){var b=gf("FB");sd(b,blo);if(blo<0){a=a.href.replace(".h","-frame.h");ih(b,"<iframe id=FBF src='"+a+"' width=750 height=500 frameborder=0>webmaster@timeanddate.com</iframe>")}blo=!blo;return false}function blc(){blo=0;bls();blo=-1}function ev(a){var b={};if(a)b.k=a.which;else{a=window.event;b.k=a.keyCode}if(b.e=a)b.s=a.target||a.srcElement;return b}
function bli(){var a,b,c,d,e,f,g,k,h=function(l){a=ev(l);if(a.e)if(b=a.s)if(c=b.href)try{if(window.open(c,"blhw")){ifpd(a.e);return false}}catch(u){}return 1};if(d=wl()){e="?url="+d.pathname;if(d=d.search)e+=encodeURIComponent(d);d=function(l,u,s,o){document.write('<a href="'+l+'"  alt="'+s+'"'+o+">"+u+"</a>")};d("/information/feedback.html"+e,"Feedback","Send feedback to us",' onclick="return bls(this)"');e.length>8?d("/createshort.html"+e,"Short URL","Create a short URL to this page",""):d("/information/linkpolicy.html",
"Link policy","About linking","");if(d=gf("TM")){g=d.getElementsByTagName("area");k=g.length;e+="&title="+encodeURIComponent(document.title);for(f=0;f<k;f++){d=g.item(f);d.href+=e;ael(d,"click",h,true)}}}}function ott(a,b){var c,d;oael(a,"mouseout",function(){pM.z()});c=b;if(ttt&&ttt[b])c=ttt[b];c="<div id=ttb onmouseover='pM.y()' onmouseout='pM.z()'>"+c+"</div>";d=ap(a);c=pM.h(c);jp(d,c,a,-1,0);ep(c,d)}
function jcb(a,b){var c,d=gx();if(d){gp(d,a,function(){(c=rs4(d))&&b(c)});return true}else return false}function phg(a,b,c){var d=ph[a];d?c(d):jcb(b,function(e){ph[a]=e;c(e)})}function calp(a,b){phg("calp","/field/calpop.php",function(c){pM.A(c,a);CPop.init(pM,b,document.f)})}function va(a){if(a)(a=elc[a])&&a()}
function abrd(a,b){return'<table id=CB><thead><tr><td id=CT><a href="javascript:modph()"><img class=fr src="//c.tadst.com/gfx/x2.png" alt=close width=18 height=18></a><div class=tc><strong>'+a+"</strong></div></td></tr><tr><td id=jcdiv>"+b+"</td></tr></table>"}
function modps(a,b,c){var d,e;if(b)a=abrd(c?c:"Info",a);a="<div id=mpofl>"+a+"</div>";d=document.documentElement;b=window.innerWidth||document.body.clientWidth;c=document.height||document.body.scrollHeight;e=d?d.clientHeight:600;if(e>c)c=e;window.getComputedStyle||(a="<img src='/gfx/blacktrans40.png' width="+b+" height="+c+">"+a);d=gf("mpo");ih(d,a);if(a=gf("mpofl")){sd(d,2);e=window.innerHeight||e;es(d,{w:b,h:c});ep(a,{x:(b-a.offsetWidth)/2,y:(e-a.offsetHeight)/2})}}
function modpop(a,b,c){a&&jcb(a,function(d){modps(d,b,c)});return false}function modph(){he("mpo",0)}function popad(a,b,c){var d=wl();c+="?ref="+escape(d.pathname+d.search);ael(gf(a),"click",function(e){modpop(c,1,b);ifpd(e);return false},true)}function hsl(a,b){var c;if(a){a.style.overflow="hidden";c=gcs(a,"height");h_speed=1;var d=function(){c-=h_speed;h_speed++;if(c>0){es(a,{h:c});window.setTimeout(d,20)}else sd(a,0)};window.setTimeout(d,b)}}
function main(){popad("poplogin","Login","/custom/loginframe.html");popad("popreg","Register a new account","/custom/createframe.html");popad("popout","Logout","/custom/logoutframe.html");popad("popin","You are logged in","/custom/loggedinframe.html");hsl(gf("svbx"),3E3)}ael(window,"load",main);
